@startmindmap
caption email : contact.sukanth@gmail.com
title: Family Tree
* guravayya
  ** pedda kottaiah
    *** kasiah
        **** prakash rao
            ***** Suseela
            ***** ?
            ***** kasiah
                ****** rama
                    ******* Sireesha
                    ******* Chandra Kanth
                ****** prakash
                    ******* Supriya
                    ******* Karthik
                ****** kumar
                    ******* Meghana
                ****** sekhar
                    ******* Tejesh
                    ******* Akash
            ***** Ramana
            ***** ?
  ** chinna kottaiah
    *** dattata kumarudu venkata subbarao (#1)
        **** anasuryamma
            ***** Mohan Rao
                ****** Nagamani
                ****** Jaalu
            ***** Muralidhar Rao
                ****** Prasad
            ***** Ranga Rao
                ****** Seshu
                ****** Kusuma
                ****** Upendra
            ***** Srinivasa Rao
                ****** Deepthi
                ****** Sudha Rani
                ****** Vamsi Krishna
            ***** Rama Krishna
                ****** Sharmila
                ****** Sireesha
                ****** Swapna
                ****** Swetha
            ***** Prabhakar Rao
                ****** Aparna
                ****** Sunil Mahanth
            ***** Sarada
                ****** Naga Mani
                ****** Naga Leela
            ***** Aruna
                ****** Pushpa
                ****** Lakshmi Prasanna
                ****** Durga
                ****** Ratna Kumar
        **** seetha rathamma
            ***** Rani
                ****** Venkateswara Rao
                ****** Eswar
                ****** Rajini
            ***** Padma
                ****** Mukunda
                ****** Dhanalakshmi
        **** khadharbabu
            ***** Kanthi Madhuri
                ****** Gehari
            ***** Lakshmi Neelima
                ****** Vishruth
        **** chitti babu
            ***** Kanthi Priya
                ****** Samanvithanjali
            ***** Santhi Priya
                ****** Anvitha
                ****** AAdhya
        **** venkateswara rao
            ***** sukanth
            ***** sumanth
  ** mattayya
    *** ?
    *** Venkata Subbarao ( #1 Original Son)
    *** Ramulu
        **** Pedda anjaneyulu
        **** Chinna anjaneyulu
        **** chitti anjaneyulu
        **** veera anjaneyulu

    *** Suryam
        **** Ravi (dattata kumarudu)
  ** rammiah
    *** Subbarao
        **** Ranga

header
Drafted by Sukanth Gunda
endheader

center footer Sukanth Gunda

@endmindmap